version: '3'
services:
  wetty:
    image: wettyoss/wetty
    command: '--ssh-host=${SSHHOST_IP} --ssh-user=manager --ssh-pass=manager123'
    ports:
      - 3010:3000
    restart: always
    networks:
      ssh-network:
        ipv4_address: ${WEBSSH_IP}
    depends_on:
      - sshhost
  sshhost:
    image: asabhi6776/ssh_ubuntu:latest
    container_name: ssh_host
    entrypoint:
    - /usr/sbin/sshd
    - -D
    networks:
      ssh-network:
        ipv4_address: ${SSHHOST_IP}
networks:
  ssh-network:
    external:
      name: ssh-network